### ISSUE TITLE
Failed Publish (missing authorization header)

### ISSUE THREAD

**Issue by mathewmeconry** [FleekHQ/action-deploy#1]
Hi

This action stopped working yesterday (maybe because of the API change of fleek).
It that there wasn't a valid authorization header provided:
![image](https://user-images.githubusercontent.com/4057473/135402398-4e9fadea-6bb8-4463-9929-93e0f43d7cd0.png)

You can see the affected workflows here:
https://github.com/aragon/client/pull/1651/checks?check_run_id=3752757250
https://github.com/aragon/client/runs/3748283551?check_suite_focus=true

**Comment by dush88c** [comment]
The same issue while calling to INIT function from FLEEK CLI .
FLEEK LOGIN was depreciated. But no API header token appended to the header while calling from the existing CLI version

**Comment by mathewmeconry** [comment]
works again
